name: Build & Test Debug

env:
  DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true

on:
  push:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      # no docs on which one of these is supposed to work, so
      # why not just do both
      - 'RobustToolbox'
      - 'RobustToolbox/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      - 'RobustToolbox'
      - 'RobustToolbox/**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            rid: linux-x64
          - os: windows-2022
            rid: win10-x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3.0.2
      
    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Install dependencies
      run: dotnet restore --no-cache -r ${{ matrix.rid }} --verbosity detailed --disable-parallel

    - name: Build Project
      run: dotnet build --configuration Debug --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Content.Tests
      run: dotnet test --no-build Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: pwsh
      run: |
        dotnet test --no-build Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0
